### ISSUE TITLE
Wrap insert form

### ISSUE THREAD

**Issue by grierson** [julienvincent/nvim-paredit#10]
Wrap the current form and place the cursor at the head of the newly created form

### Expected behaviour

1. `(+ 1 1)` (Cursor anywhere within expression)
3. **Wrap command**
5. `(| (+ 1 1))` (New surround added around existing form, cursor moved to after the first paren and in insert mode)

**Comment by julienvincent** [comment]
This can be thought of as two things:

+ Form-wise motions
+ Automatic enter-insert

I think form-wise motions should definitely be added as a companion to the element-wise motions that already exist, but I'm not so sure about the automatic enter-insert behaviour.

My thinking is that if we add the form-wise motions and a user wants the enter-insert then it should be quite straight forward to setup a keybinding in userspace config which calls `nvim-paredit`s form-wise motion API followed by a mode change.

**Comment by armed** [comment]
currently I'm experimenting with a new api which allows us to create custom keybindings. 
![image](https://github.com/julienvincent/nvim-paredit/assets/223060/4425bd1b-73cb-491f-9fc9-25dfa63bf7ab)

**Comment by armed** [comment]
@grierson form/element wrap feature is merged into master. You might check API recipes section, there are examples on how to replicate vim-sexp keybindings.
