### ISSUE TITLE
Cursor insertion

### ISSUE THREAD

**Issue by grierson** [julienvincent/nvim-paredit#11]
Move cursor to the head of the form, Add a space, and put editor into Insert mode.

1. `( + 1 1)` (Cursor anywhere within expression)
2.  **Cursor insert**
3. `(| + 1 1)`(Cursor moved to beginning of form and in insert mode)

**Comment by julienvincent** [comment]
This can be thought of as two things:

+ Form-wise motions
+ Automatic enter-insert

I think form-wise motions should definitely be added as a companion to the element-wise motions that already exist, but I'm not so sure about the automatic enter-insert behaviour.

My thinking is that if we add the form-wise motions and a user wants the enter-insert then it should be quite straight forward to setup a keybinding in userspace config which calls `nvim-paredit`s form-wise motion API followed by a mode change.

**Comment by armed** [comment]
Implemented in #14 (see recipes section in the readme)
