### ISSUE TITLE
Form selection

### ISSUE THREAD

**Issue by grierson** [julienvincent/nvim-paredit#12]
The af and if objects selects forms
The aF and iF objects select top-level forms.

### Why
[Replicate vim-sexp Text Object Selections](https://github.com/guns/vim-sexp#text-object-selections-visual-operator-pending)

Clojure uses multiples types for surrounds `( { [` being able to refer to each with just `f/F` makes text manipulation within Clojure much easier.

- di( -> dif
- di[ -> dif
- di{ -> dif

### Expected behaviour

**Current form**
1. `(+ 1 1)` (Cursor anywhere within expression)
2. **dif**
3. `()` deletes everything within form

**Top level form**

1. `(+ 1 (+ 2 3))` (Cursor within sub form)
2. **diF**
3. `()` deletes everything within top level form

**Comment by julienvincent** [comment]
Agreed this will be useful to have, and should be straight forward to add. Will get around to it when I have a moment :)

**Comment by Olical** [comment]
Just a note that I don't _think_ there's a way to select root elements / forms still. So there's no `vaF` to select a whole `defn` for example. If I'm right in that assumption maybe I can add it soon.

**Comment by Olical** [comment]
You'll have to ignore the Fennel _and_ custom macros for exporting values from the Lua module, but here's what I use in Conjure to select the root form in tree sitter across multiple languages. https://github.com/Olical/conjure/blob/58c46d1f4999679659a5918284b574c266a7ac83/fnl/conjure/tree-sitter.fnl#L77-L87

So this may be a good template to rip off to get started with.

**Comment by julienvincent** [comment]
Ah you are right I forgot about the root form selections. Shouldn't be too difficult to add, if you want to take a stab at it go ahead :)

Otherwise I can look into it when I get a moment.

**Comment by Olical** [comment]
I'm working on this at the moment but a heads up that the tests seem to fail for the slurp/barfing in the Neovim nightly build. I swapped to stable and they run just fine.

**Comment by julienvincent** [comment]
Ok I actually just disabled nightly for now and merged that PR. Running `just test` will now use stable.

**Comment by Olical** [comment]
Nice, rebased my changes on this and opening a PR with my first pass now. I have selections and deletions working, will probably add more tests, may need to add more methods for visual selections too, mostly focussed on deletions so far.

Also you may find this useful: https://github.com/Olical/nfnl/blob/main/.github/workflows/test.yaml

It's my GitHub action tests I use to run Plenary Busted (like you do) in GitHub Actions across multiple Neovim versions. The downside is that it doesn't work locally the same way, I run the tests in whatever Neovim version I have installed locally.

Just thought I'd share in case you liked the way you can just add version numbers to the list.
