### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by kolja** [julienvincent/nvim-paredit#18]
Your Installation instructions don't work for me:
```
{
  "julienvincent/nvim-paredit",
  config = function()
    require("nvim-paredit").setup()
  end
}
```
gives me this error message at startup:
```... /init.lua:24: attempt to index local 'opts' (a nil value)```

The error goes away when I pass a table like so:

```
{
  "julienvincent/nvim-paredit",
  config = function()
    require("nvim-paredit").setup({})
  end
}
```
...but it'd be sufficient to just set

```
{
  "julienvincent/nvim-paredit",
  config = true
}
```

**Comment by julienvincent** [comment]
Thanks! Resolved :)
