### ISSUE TITLE
The aF/iF/af/if objects move the cursor when indenting

### ISSUE THREAD

**Issue by Olical** [julienvincent/nvim-paredit#41]
If my cursor is deep inside a nested form and I use `=aF` to indent the top level form my cursor moves to the end of the first line of that form.

I think the cursor should remain where you left it if possible. If you agree then I'm happy to look into addressing this, just thought I'd raise an issue to discuss it first. Here's some examples:

```clojure
(defn foo [a b]
  (println "hi")
  (+ a b
     10))
```

 - `=af` on the last line moves the cursor up one line to the `+ a b`.
 - `=aF` anywhere in the form moves the cursor to the first line of the `defn` at the column you were at on the previous line.
 - The same goes for both `i` objects.

**Comment by julienvincent** [comment]
I'm not sure this is something we can really change as that behaviour is not controlled by nvim-paredit. Paredit just defines the selection range to be operated on after which point the `=` operand (or whichever operator is currently in operator-pending) takes over.

For example, you can observe the exact same behaviour when running a vim-native operation like `=a(`.

**Comment by Olical** [comment]
Ah okay, great point! Maybe I'm used to vim-sexp's behaviour where I used
=- to indent the top level form. I think that kept the cursor in place but
now I wonder if I imagined it.

Maybe I can rustle up a custom mapping that replaces =- and keeps the
cursor in place somehow.

**Comment by julienvincent** [comment]
> Maybe I can rustle up a custom mapping that replaces =- and keeps the
cursor in place somehow.

Should be fairly straight forward to do by using the `vim.api.nvim_win_get_cursor` api!

I'm gonna close this one out, feel free to re-open if you feel there is more to action here.
