### ISSUE TITLE
Bug: `dW` deletes 1 character too many

### ISSUE THREAD

**Issue by NoahTheDuke** [julienvincent/nvim-paredit#42]
Given the text (with cursor at `|`) `[|1 2 3]`, pressing `dW` will delete `1 2`, leaving `[| 3]`. This happens with collections as well: `[|(1) (2) 3]` becomes `[|2) 3]`.

**Comment by NoahTheDuke** [comment]
Is it a bug or just an implementation detail I've come to rely on that in `vim-sexp`, pressing `dW` on the final element in a collection will delete it? For example, `[1 2 |(3)]` in vim-sexp results in `[1 2 ]`, whereas in nvim-paredit, this results in `[1 2 |3)]`.

**Comment by armed** [comment]
Yep, can confirm. First take: need to detect that pending operator is delete and return column number decremented by 1.
Thoughts @julienvincent?

**Comment by armed** [comment]
Digging into vim api, event can be inclusive/exclusive.
