### ISSUE TITLE
Feature request: auto balancing

### ISSUE THREAD

**Issue by fgasperino** [julienvincent/nvim-paredit#48]
Similar to paredit.nvim and emacs paredit.el, having the option for auto balancing of Clojure data structures would be great.

**Comment by julienvincent** [comment]
Hi there.

Just so I can understand what you are asking for - are you referring to parenthesis balancing like what is depicted in https://shaunlebron.github.io/parinfer/, auto-pairing/bracket matching like from https://github.com/windwp/nvim-autopairs or something else entirely?

**Comment by fgasperino** [comment]
Thanks for the response. I had not seen autopairs before, and it appears it'll pair up nicely with your plugin. So far, enjoying it!

**Comment by AlexChalk** [comment]
Hi @julienvincent, what are your thoughts on parinfer-like parenthesis balancing? Do you think there's a good reason for supporting it, or do I just need to get more used to paredit-style editing? (I mainly miss it when I want to comment out lines.) Thanks!
