### ISSUE TITLE
`ts.swap_nodes` throws error on latest Neovim master

### ISSUE THREAD

**Issue by NoahTheDuke** [julienvincent/nvim-paredit#54]
I run neovim master, and have run into an issue with all of the functions that use `ts.swap_nodes`. Since https://github.com/neovim/neovim/pull/27614, neovim now requires that the buffer number passed to `apply_text_edits` (which ts.swap_nodes uses) is non-nil and **non-0**. Every call to `ts.swap_nodes` in nvim-paredit that I saw uses `0` to specify "the current buffer". The fix should be as easy as passing `vim.api.nvim_get_current_buf()` to all of the `ts.swap_nodes` calls in place of `0`.

**Comment by NoahTheDuke** [comment]
I implemented such a change locally and the tests pass with 0.9.5 but fail for other reasons with 0.10 (master). I'm not entirely sure what else has changed, but I can open a PR if you want just this fix.

**Comment by julienvincent** [comment]
Yea the tests for neovim nightly have been failing here for a while. I haven't had a proper chance to investigate it. Those tests are currently disabled for the CI tests that run here.

Thanks for the fix!

**Comment by NoahTheDuke** [comment]
Glad to help.
