### ISSUE TITLE
Strict Mode

### ISSUE THREAD

**Issue by raystubbs** [julienvincent/nvim-paredit#62]
Thanks for the work on this, its really great.

One thing I do miss though, and don't see mentioned in the readme, is bracket auto-closing and safe deletion (can't delete closing bracket without also deleting the opening one) as is pretty common in similar projects.  Any chance of supporting this in future?

**Comment by julienvincent** [comment]
Hi there,

I don't think this is something that I would be interested in adding to this project.

This sounds like something that could be easily implemented in a separate plugin without any concerns of conflicts with nvim-paredit.

**Comment by raystubbs** [comment]
Fair enough, thanks for the reply.

**Comment by NoahTheDuke** [comment]
I use https://github.com/windwp/nvim-autopairs for this functionality.
