### ISSUE TITLE
Plugin doesn't move anything

### ISSUE THREAD

**Issue by willocho** [julienvincent/nvim-paredit#82]
Hi there. I just installed this plugin today and I'm trying to use it but as far as I can tell it isn't working/configured correctly.

I'm using lazy and this is what my config looks like
```
    {
        "julienvincent/nvim-paredit",
        config = function()
            require("nvim-paredit").setup{
                use_default_keys=true
            }
        end
    }
```

Using any of the default key mappings, like `>)` doesn't do anything. I can load the module and run it from the commnad line, but again nothing happens. E.g., running `:lua require('nvim-paredit').api.slurp_forwards()` does nothing. Is there some additional configuration I need?

I'm running nvim in a terminal on a Mac M2, if that matters.

**Comment by julienvincent** [comment]
Can you answer these:

+ What language are you trying to use paredit with?
+ Do you have nvim-treesitter and the grammar for your language installed?
+ What commit of paredit are you on?
+ If it's shareable - can you share your nvim config repo?

The fact that requiring the module api directly does nothing means that this is probably missing language grammars or something along those lines.

Do you get any errors at any point?

**Comment by willocho** [comment]
I didn't have the treesitter grammar installed for clojure... Thank you for responding so quickly!
